### ISSUE TITLE
Constant Given for DS3231 Aging Register is Incorrect

### ISSUE THREAD

**Issue by mrwgx3** [SodaqMoja/Sodaq_DS3231#10]
The [DS3231 aging register definition][aging_reg] is incorrect. In 'Sodaq_DS3231.cpp' you need to replace
``` 
#define DS3231_AGING_OFFSET_REG 0x0F
``` 
with
``` 
#define DS3231_AGING_OFFSET_REG 0x10
```
[aging_reg]: https://github.com/SodaqMoja/Sodaq_DS3231/blob/master/src/Sodaq_DS3231.cpp#L41#L41  "DS3231 Aging Register Definition"

**Comment by SodaqMoja** [comment]
Good catch. Updated in v1.2.2
