### ISSUE TITLE
Arduino error: 'String' has not been declared

### ISSUE THREAD

**Issue by armorer1984** [SodaqMoja/Sodaq_DS3231#4]
I am having issues compiling with this library with Arduino IDE 1.6.5.

The error given when trying to compile is:

```
In file included from temperature.pde:1:0:
C:\Users\Chris\Documents\Arduino\libraries\Sodaq_DS3231-master\src/Sodaq_DS3231.h:42:22: error: 'string' has not been declared
     void addToString(string & str) const;
```

**Comment by SodaqMoja** [comment]
That is strange because the source code contains "String" not "string"
    `void addToString(String & str) const;`
You probably have changed the file.

**Comment by giatros** [comment]
I run into the same problem, kind of.The following code does not compile:

```
#include "Sodaq_DS3231.h"
void setup() {
  // put your setup code here, to run once:
  rtc.begin();
}
void loop() {
  // put your main code here, to run repeatedly:
 delay(1000);
}
```
producing this error:

```
Arduino: 1.6.5 (Linux), Board: "Arduino/Genuino Uno"

In file included from test.ino.ino.ino:1:0:
/home/docs/programming/arduino/libraries/Sodaq_DS3231/src/Sodaq_DS3231.h:42:22: error: 'String' has not been declared
     void addToString(String & str) const;
                      ^
Error compiling.
```

while this code compiles just fine:
```
#include "Wire.h"
#include "Sodaq_DS3231.h"

void setup() {
  // put your setup code here, to run once:
  rtc.begin();
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(1000);
}
```

Apparently wire.h is mandatory, but the error message does not point to the right direction of the error.

**Comment by SodaqMoja** [comment]
In your case it is a chain of includes. Wire.h -> Stream.h -> Print,h -> WString.h
Wire.h is not mandatory from the ino.

I now see that this was already solved (by Roman) and I forgot to bump the version to v1.2.1.
It should be available as soon as Arduino has picked it up. (Usually within a day.)

**Comment by giatros** [comment]
I don't understand your comment SodaqMoja. Why there is an compilation error without if I ommit the Wire.h in the code?

**Comment by SodaqMoja** [comment]
Never mind. It is a C programming detail.

Please grab the library update and the problem should be gone.
